name: Build - Vite
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.GH_TOKEN}}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - run: |
          cd dist
          git init
          git config --global user.email ${{vars.EMAIL}}
          git config --global user.name ${{vars.USERNAME}}
          git status

          git remote add origin https://${{secrets.GH_TOKEN}}@${{vars.REPO_URL}}
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
